version: "3.8"

services:
  postgres:
    image: postgres
    container_name: node_course_postgres_container
    environment:
      POSTGRES_USER: brzubko
      POSTGRES_PASSWORD: 123Pass345
      POSTGRES_DB: nodejs_course_database
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: node_course_pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: zubkobohdan12@gmail.com
      PGADMIN_DEFAULT_PASSWORD: MyPass123
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
